# Updated src/config/tasks.yaml
# Refined: Updated descriptions; removed obsolete tasks.
classify_query:
  description: |
    Inputs: Query: {user_query} | File (if any): {file_content} | History: {full_history} | Profile: {user_profile} | Available ops: {op_names}
    Classify: 'direct' (simple aid, no ops) or 'agentic' (needs ops execution).
    For direct: Provide full, accurate direct_response using context.
    For agentic: Generate ordered operations [ {{"name": "op1", "parameters": {{"param": "value"}} }} , ... ] (use available ops, plan logical flow). Summarize intent: user_summarized_requirements (detailed, from history/profile/query/file).
    Output STRICT JSON only: {{"mode": "agentic|direct", "operations": [ ... ], "user_summarized_requirements": "..." }} or {{"mode": "direct", "direct_response": "..." }}. No extra text.
  expected_output: "Strict JSON object."
  agent: classifier

synthesize_response:
  description: |
    User Requirements: {user_summarized_requirements}
    Operation Results: {op_results}
    Synthesize: display_response (coherent final answer, mention ops e.g., "Performed web_search + create_task: [results]"), extracted_fact (list of 1-3 short, structured facts for KB, e.g., [ "New task: Buy milk due 2025-09-14" ]).
    Output STRICT JSON only: {{"display_response": "...", "extracted_fact": [ "fact1", ... ] }}. No extra text.
  expected_output: "Strict JSON object."
  agent: synthesizer
summarize_history:
  description: |
    Summarize history concisely (100-300 tokens): {full_history}
  expected_output: "Summary string."
  agent: summarizer
